 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: ghost-ingress
 spec:
   rules:
   - host: example.com
     http:
       paths:
       - path: /
         backend:
           serviceName: ghost-svc
           servicePort: 80
